-- ============================================================================
-- Resume Builder — complete database schema
-- ============================================================================
-- This is the single source of truth for the database structure. Run this
-- once against a fresh, empty PostgreSQL database to create everything the
-- application needs:
--
--   createdb resume_builder
--   psql "$DATABASE_URL" -f server/db/schema.sql
--   psql "$DATABASE_URL" -f server/db/seed.sql   # optional sample data
--
-- No other setup step or historical migration file is required.
-- ============================================================================

-- Shared trigger function: keeps an `updated_at` column current on UPDATE.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── users ───────────────────────────────────────────────────────────────
-- Login accepts either username or email (see server/src/repositories/
-- user.repository.ts). Both are looked up and enforced as unique
-- case-insensitively via the functional indexes below, in addition to the
-- plain UNIQUE constraints; email is also always normalized to lowercase
-- before it's stored (see server/src/services/auth.service.ts).
CREATE TABLE IF NOT EXISTS users (
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    username      VARCHAR(100) UNIQUE NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_key ON users (LOWER(username));

-- ── templates ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS templates (
    template_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name VARCHAR(100) NOT NULL,
    thumbnail_url TEXT
);

-- ── resumes ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS resumes (
    resume_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    template_id INTEGER REFERENCES templates(template_id) ON DELETE SET NULL,
    title       VARCHAR(150) NOT NULL,
    full_name   VARCHAR(150),
    email       VARCHAR(255),
    phone       VARCHAR(30),
    location    VARCHAR(150),
    summary     TEXT,
    -- Simple resume layout customization (font size, section spacing, accent
    -- color), e.g. {"fontSize":"medium","spacing":"normal","accentColor":"#111827"}.
    -- Nullable: existing resumes have no value here, and the application
    -- (client + PDF generator) falls back to sensible defaults when it's
    -- null, so no backfill/migration of existing rows is required.
    customization JSONB,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_resumes_updated_at ON resumes;
CREATE TRIGGER trg_resumes_updated_at
  BEFORE UPDATE ON resumes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ── experience ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS experience (
    experience_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id     INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    company_name  VARCHAR(150) NOT NULL,
    job_title     VARCHAR(150) NOT NULL,
    start_date    DATE,
    end_date      DATE,
    is_current    BOOLEAN DEFAULT FALSE,
    description   TEXT,
    order_index   INTEGER DEFAULT 0
);

-- ── education ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS education (
    education_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id        INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    institution_name VARCHAR(200) NOT NULL,
    degree           VARCHAR(150),
    field_of_study   VARCHAR(150),
    start_date       DATE,
    end_date         DATE,
    gpa              VARCHAR(20),
    order_index      INTEGER DEFAULT 0,
    education_level  VARCHAR(50) CHECK (education_level IS NULL OR education_level IN ('primary', 'secondary', 'higher_secondary', 'degree'))
);

-- ── projects ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
    project_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id    INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    project_name VARCHAR(150) NOT NULL,
    description  TEXT,
    project_link TEXT,
    technologies TEXT,
    order_index  INTEGER DEFAULT 0
);

-- ── skills ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skills (
    skill_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id         INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    skill_name        VARCHAR(100) NOT NULL,
    category          VARCHAR(50),
    proficiency_level VARCHAR(50)
);

-- ── certifications ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS certifications (
    certification_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id            INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    certification_name   VARCHAR(200) NOT NULL,
    issuing_organization VARCHAR(200),
    issue_date           DATE,
    credential_id        VARCHAR(150),
    credential_url       TEXT,
    order_index          INTEGER DEFAULT 0
);

-- ── achievements ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS achievements (
    achievement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id      INTEGER NOT NULL REFERENCES resumes(resume_id) ON DELETE CASCADE,
    title          VARCHAR(200) NOT NULL,
    description    TEXT,
    achieved_date  DATE,
    order_index    INTEGER DEFAULT 0
);

-- ── indexes ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_resumes_user_id ON resumes(user_id);
CREATE INDEX IF NOT EXISTS idx_resumes_template_id ON resumes(template_id);
CREATE INDEX IF NOT EXISTS idx_experience_resume_id ON experience(resume_id);
CREATE INDEX IF NOT EXISTS idx_education_resume_id ON education(resume_id);
CREATE INDEX IF NOT EXISTS idx_projects_resume_id ON projects(resume_id);
CREATE INDEX IF NOT EXISTS idx_skills_resume_id ON skills(resume_id);
CREATE INDEX IF NOT EXISTS idx_certifications_resume_id ON certifications(resume_id);
CREATE INDEX IF NOT EXISTS idx_achievements_resume_id ON achievements(resume_id);
